# Generated by Django 3.2.7 on 2022-05-28 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('about_me', models.TextField(default='tell us about yourself', verbose_name='About me')),
                ('profile_img', models.ImageField(default='/profile_img.png', upload_to='', verbose_name='Profile Image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='NG', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Lagos', max_length=50, verbose_name='City')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you an Agent ?', verbose_name='Agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
