# Generated by Django 3.2.7 on 2022-06-08 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAgent',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200, unique=True, verbose_name='Host Business Name')),
                ('license', models.CharField(blank=True, max_length=30, null=True, verbose_name='Real Estate License')),
                ('office_address', models.CharField(max_length=400, verbose_name='Office Address')),
                ('num_of_reviews', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='profiles.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
