# Generated by Django 3.2.7 on 2022-06-08 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_hostagent'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.hostagent', verbose_name='Agent receiving the review'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('client', 'agent')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='properte',
        ),
    ]
