# Generated by Django 3.2.7 on 2022-06-11 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_hostagent'),
        ('ratings', '0002_auto_20220608_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='profiles.hostagent', verbose_name='Agent receiving the review'),
        ),
    ]
